language: node_js
node_js:
  - "node"
env:
  global:
    - CC_TEST_REPORTER_ID=03a32907927554970740910b14bda3d50a900226af2d4063211c8720fe21cebb
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test:unit
  - npm run coveralls
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
